### ISSUE TITLE
Framework To Add Support / Make Use of............

### ISSUE THREAD

**Issue by varunsridharan** [wponion/wponion#20]
### Selected CSS Libs
- [x] [PrettyCheckbox](https://lokesh-coder.github.io/pretty-checkbox/)

### CSS Library's
- [x] [FontAwesome](http://fontawesome.com/)
- [x] [Animate.CSS](https://daneden.github.io/animate.css/)
- [ ] [MagicInput](http://wangchujiang.com/magic-input/) | [PrettyCheckbox](https://lokesh-coder.github.io/pretty-checkbox/)
- [ ] [Effeckt.css](http://h5bp.github.io/Effeckt.css/)
- [ ] [FlagIcons](https://github.com/lipis/flag-icon-css)
- [ ] [IonIcons](https://github.com/ionic-team/ionicons)
- [ ] [Google Materiel Design Icons](http://google.github.io/material-design-icons/)
- [ ] [CSS Loaders](https://connoratherton.com/loaders) + [SpinKit](http://tobiasahlin.com/spinkit/)
- [ ] [ImageHover](http://imagehover.io/)
- [ ] [IconHover](https://tympanus.net/Development/IconHoverEffects/)
- [ ] [PageAnimations](http://git.blivesta.com/animsition/)
- [ ] [CSSLoders](http://www.raphaelfabeni.com.br/css-loader/)

### JS Library's
- [x] [Select2](http://select2.org)
- [x] [Selectize](https://selectize.github.io/selectize.js)
- [ ] [Bootstrap Datepicker](https://bootstrap-datepicker.readthedocs.io/en/latest/) 
- [ ] [Bootstrap Timepicker](https://github.com/jdewit/bootstrap-timepicker)
- [ ] [Bootstrap Colorpicker](https://itsjavi.com/bootstrap-colorpicker/) 
- [ ] [Bootstrap Switch](https://github.com/Bttstrp/bootstrap-switch)
- [ ] [Boostrap Maxlength](https://github.com/mimo84/bootstrap-maxlength)
- [ ] [ion RangeSlider](https://github.com/IonDen/ion.rangeSlider)
- [ ] [jQuery Validation](https://jqueryvalidation.org/)
- [x] **jQuery Inputmask**
- [ ] [jQuery MarkdownEditor](https://simplemde.com/)
- [ ] [ImageCropper](https://fengyuanchen.github.io/cropperjs/)
- [ ] [Bootstrap Touch Spin](https://github.com/istvan-ujjmeszaros/bootstrap-touchspin)

#### Selectize Addons
- [x] **click_to_edit** | [Selectize Pull #946](https://github.com/selectize/selectize.js/pull/946) | [Source Code](https://github.com/krissalvador27/selectize.js/blob/5fe5862cb0d918c3f500c53c04f979e8d401a1db/src/plugins/click_to_edit/plugin.js) 
- [x] **condensed_dropdown**  | [Selectize Pull #944](https://github.com/selectize/selectize.js/pull/944) | [Source Code](https://github.com/rantav/selectize.js/tree/0e45bf604acfd507d150561e39fe83b758cac24b/src/plugins/condensed_dropdown) 
- [x] **dark_theme**  | [Selectize Pull #447](https://github.com/selectize/selectize.js/pull/447) | [Source Code](https://github.com/mistic100/selectize.js/tree/3bdf50a5e5850905aaf203eab679dc8fe9fae2d7/dist/css) 
- [x] **bootstrap4_theme** | [Selectize Issue #905](https://github.com/selectize/selectize.js/issues/905) | [Source Code](https://github.com/papakay/selectize-bootstrap-4-style)

### Extra Color Picker Options
- [ ] [jColor - a jQuery Color Picker ](https://codecanyon.net/item/jcolor-a-jquery-color-picker/10688026)
- [ ] [ColoringPick](https://codecanyon.net/item/coloringpick-jquery-gradient-color-picker/21130553?s_rank=3)
- [ ] [MeterialPallet](https://codecanyon.net/item/material-color-picker-plus/20316509?s_rank=5)
